language: ruby
install:
  - sudo apt-get update
  - sudo apt-get install -y apt-transport-https
  # lxc installation by
  # https://github.com/zpatten/lxc/blob/master/spec/support/install-lxc.sh
  - echo '#!/bin/sh' | sudo tee /usr/sbin/policy-rc.d
  - echo 'exit 101' | sudo tee -a /usr/sbin/policy-rc.d
  - sudo chmod 755 /usr/sbin/policy-rc.d
  - curl -s https://get.docker.io/ubuntu/ | sudo sh
  - sudo apt-get install -y python-setuptools
  - sudo easy_install fabric
before_script:
  - sudo docker build -t sshd .
  - container=`sudo docker run -d sshd`
  - ip=`sudo docker inspect $container | grep IPAddress | cut -d '"' -f 4`
  - fabric -H $ip -u test -p pass provision
script:
  - echo OK
