language: ruby
before_install:
  - sudo apt-get update
  # lxc installation by
  # https://github.com/zpatten/lxc/blob/master/spec/support/install-lxc.sh
  - cat <<EOF | sudo tee /usr/sbin/policy-rc.d \
#!/bin/sh \
exit 101 \
EOF
  - sudo chmod 755 /usr/sbin/policy-rc.d
  - sudo apt-get install -y lxc
  - sudo apt-get install -y python-software-properties
  - sudo add-apt-repository -y ppa:dotcloud/lxc-docker
  - sudo apt-get update
  - sudo apt-get install -y lxc-docker
  - sudo docker build -t sshd .
  - container=`sudo docker run -d sshd`
  - ip=`sudo docker inspect $container | grep IPAddress | cut -d '"' -f 4`
  - sudo apt-get install -y python-setuptools
  - sudo easy_install fabric
  - fabric -H $ip -u test -p pass provision
script:
  - echo OK
